#!/bin/bash

# NOTE: Install flask first by - pip install Flask

case "$1" in
    dev)
        export FLASK_APP=app.py
        # Activates debug mode (includes hot reloading too)
        export FLASK_ENV=development
        flask run
    ;;
    *)
        export FLASK_APP=app.py
        flask run
    ;;
esac

